import { backendAxios } from "./backendAccessConfiguration";

export const endpoints = {
  googleValidate: "api/auth/google/validate",
  googleRegister: "api/auth/google/register",
  githubValidate: "api/auth/github/validate",
  githubRegister: "api/auth/github/register",
  currentUser: "api/auth/currentUser",
  users: "api/Users",
  collectionTypes: "api/CollectionTypes",
  collections: "api/Collections",
  collectionsCoverImage: `${backendAxios.defaults.baseURL}/api/Collections/CoverImage`,
  collectionsCoverImageUpload: "api/Collections/CoverImage/Upload",
  icons: `${backendAxios.defaults.baseURL}/icons`,
  items: "api/Items",
  itemsCoverImage: `${backendAxios.defaults.baseURL}/api/Items/CoverImage`,
  itemsTempImage: `${backendAxios.defaults.baseURL}/api/Items/TempImage`,
  itemsUpsert: "api/Items/Upsert",
  itemOptions: "api/ItemOptions",
  itemsImageCheck: "api/Collections/ImageCheck",
  attributes: "api/Attributes",
  feed: "api/Feed",
  feedSearch: "api/Feed/Search",
  feedSearchTag: "api/Feed/SearchTag",
  reactions: "api/Reactions",
  follows: "api/Follows",
  userContact: "api/UserContact",
  trades: "api/Trades",
  offers: "api/Offers",
};
