export const querykeys = {
  collectionTypesData: "collectionTypesData",
  collectionsData: "collectionsData",
  collectionsWithCurrentName: "collectionsWithCurrentName",
  itemsData: "itemsData",
  itemOptionsData: "itemOptionsData",
  attributesData: "attributesData",
  feedListData: "feedListData",
  otherUserCollectionsData: "otherUserCollectionsData",
  otherUserItemsData: "otherUsersItemsData",
  itemTagsSearchData: "itemTagsSearchData",
  mixedSearchData: "mixedSearchData",
  myTradesData: "myTradesData",
  myOffersData: "myOffersData",
  collectionForItemData: "collectionForItemData",
  tradesData: "tradesData",
  tradeData: "tradeData",
  followsData: "followsData",
  tradeReviewData: "tradeReviewData",
  userReviewsData: "userReviewsData",
  itemTagsData: "itemTagsData",
};
